/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/metadata/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Conteos por un campo de la metadata
         * @description Alimenta el componente de barras: comparacion, distribucion y composicion.
         */
        get: operations["metadata_breakdown_metadata_breakdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * El documento y sus fragmentos
         * @description El texto original detras de cualquier dato del tablero, en la ventana que contiene `around`.
         *
         *     Sin `around`, la ventana empieza en `start`. Centrarla en el fragmento citado es lo que cierra
         *     la trazabilidad que exige la especificacion: el dato lleva a su `chunk_id`, no solo al `doc_id`.
         */
        get: operations["document_documents__doc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Matriz de calor de entidades
         * @description Cruza las entidades mas presentes con otra categoria: que entidad domina cada fuente.
         */
        get: operations["entity_matrix_entities_matrix_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/cooccurrence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Red de co-ocurrencia de entidades
         * @description Que entidades aparecen juntas, y en cuantos documentos.
         */
        get: operations["entity_cooccurrence_entities_cooccurrence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lugares nombrados en el corpus
         * @description Alimenta el mapa coropletico. Solo devuelve lugares que el corpus nombra.
         */
        get: operations["places_places_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Documentos por ano
         * @description Alimenta la linea de tiempo. Sin fechas precomputadas la serie sale vacia a proposito:
         *     inventar una fecha desde el texto seria presentar una variable sin sustento.
         */
        get: operations["timeline_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/quadrant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cuadrante de priorizacion de entidades
         * @description Intensidad contra tendencia: a que entidades mirar primero, sin puntuar ninguna.
         *
         *     El eje horizontal son los documentos que nombran la entidad y el vertical, que proporcion de
         *     ellos esta en la mitad reciente del corpus. Los dos son conteos verificables; las lineas de
         *     corte son las medianas, asi que el cuadrante compara entidades entre si y no contra un umbral
         *     inventado.
         */
        get: operations["entity_quadrant_entities_quadrant_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Responde una consulta del usuario
         * @description Una consulta, una respuesta completa: texto, insumo de calidad e insumo de eficiencia.
         *
         *     El orquestador nunca propaga una excepcion: un 500 no trae `metadata`, y sin `metadata` la
         *     pregunta cuenta como fallo entero en el bloque de eficiencia. Un error llega hasta aqui como
         *     una traza con `estado` distinto de `ok`.
         */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent-card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ficha del sistema multiagente
         * @description La arquitectura declarada: el agente, su orquestador y los subagentes con sus herramientas.
         *
         *     Se sirve desde el mismo despliegue que responde para que no pueda quedar desfasada de lo que el
         *     sistema hace de verdad: las herramientas salen del propio registro.
         */
        get: operations["agent_card_agent_card_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Lo que mira el healthcheck del contenedor antes de dar el servicio por arriba.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentCard
         * @description La ficha de la seccion 2.3: formato propio de ADL, no el estandar A2A.
         */
        AgentCard: {
            agente: components["schemas"]["CardAgent"];
            orquestador: components["schemas"]["CardOrchestrator"];
            /** Subagentes */
            subagentes?: components["schemas"]["CardSubagent"][];
        };
        /**
         * AgentTokens
         * @description Desglose por agente y modelo: permite calcular el costo con la tarifa de cada uno.
         */
        AgentTokens: {
            /** Agente */
            agente: string;
            /** Modelo */
            modelo: string;
            /**
             * Input
             * @default 0
             */
            input: number;
            /**
             * Output
             * @default 0
             */
            output: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /**
         * Breakdown
         * @description Comparacion, distribucion y composicion sobre la metadata del corpus.
         */
        Breakdown: {
            /** Field */
            field: string;
            /** Phenomenon */
            phenomenon?: number | null;
            /** Total Fragments */
            total_fragments: number;
            /** Total Documents */
            total_documents: number;
            /** Buckets */
            buckets: components["schemas"]["BreakdownBucket"][];
        };
        /**
         * BreakdownBucket
         * @description Una barra: cuantos fragmentos y de cuantos documentos distintos.
         */
        BreakdownBucket: {
            /** Label */
            label: string;
            /** Fragments */
            fragments: number;
            /** Documents */
            documents: number;
        };
        /**
         * BreakdownField
         * @description Campos por los que se puede agrupar el corpus. Lista cerrada: son columnas indexadas.
         * @enum {string}
         */
        BreakdownField: "phenomenon" | "observatory" | "language" | "format";
        /** CardAgent */
        CardAgent: {
            /** Nombre */
            nombre: string;
            /** Descripcion */
            descripcion: string;
            /** Version */
            version: string;
            /** Endpoint */
            endpoint: string;
            /** Input Modes */
            input_modes: string[];
            /** Output Modes */
            output_modes: string[];
        };
        /** CardOrchestrator */
        CardOrchestrator: {
            /** Nombre */
            nombre: string;
            /** Descripcion */
            descripcion: string;
            /** Modelo */
            modelo: string;
            /** Proveedor */
            proveedor: string;
            /** Tools */
            tools?: components["schemas"]["CardTool"][];
        };
        /** CardSubagent */
        CardSubagent: {
            /** Id */
            id: string;
            /** Nombre */
            nombre: string;
            /** Descripcion */
            descripcion: string;
            /** Modelo */
            modelo: string;
            /** Proveedor */
            proveedor: string;
            /** Activado Por */
            activado_por: string;
            /** Ejemplos De Activacion */
            ejemplos_de_activacion?: string[];
            /** Tools */
            tools?: components["schemas"]["CardTool"][];
        };
        /** CardTool */
        CardTool: {
            /** Name */
            name: string;
            /** Descripcion */
            descripcion: string;
            /** Input Parameters */
            input_parameters?: {
                [key: string]: string;
            };
        };
        /**
         * ChatRequest
         * @description La consulta. `input` es el nombre que usa el bloque de evaluacion para la pregunta.
         */
        ChatRequest: {
            /**
             * Input
             * @description La pregunta del usuario
             */
            input: string;
        };
        /**
         * ChatResponse
         * @description Los tres bloques que ADL espera de cada consulta.
         */
        ChatResponse: {
            /** Respuesta */
            respuesta: string;
            evaluacion: components["schemas"]["Evaluation"];
            metadata: components["schemas"]["Metadata"];
        };
        /**
         * Document
         * @description El texto original que sustenta una visualizacion, en una ventana de sus fragmentos.
         *
         *     `total` y `start` situan la ventana dentro del documento: el lector sabe cuanto queda a cada
         *     lado y puede pedir el tramo anterior o el siguiente sin traerse el documento entero.
         */
        Document: {
            /** Doc Id */
            doc_id: string;
            /** Title */
            title?: string | null;
            /** Observatory */
            observatory?: string | null;
            /** Phenomenon */
            phenomenon: number;
            /** Language */
            language?: string | null;
            /** Format */
            format?: string | null;
            /** Total */
            total: number;
            /** Start */
            start: number;
            /** Fragments */
            fragments?: components["schemas"]["DocumentFragment"][];
        };
        /** DocumentFragment */
        DocumentFragment: {
            /** Chunk Id */
            chunk_id: string;
            /** Position */
            position: number;
            /** Num Tokens */
            num_tokens: number;
            /** Text */
            text: string;
        };
        /**
         * Evaluation
         * @description Insumo de las metricas de calidad: relevancia, fidelidad, toxicidad y tono.
         */
        Evaluation: {
            /** Input */
            input: string;
            /** Actual Output */
            actual_output: string;
            /** Retrieval Context */
            retrieval_context?: string[];
            /** Tools Called */
            tools_called?: components["schemas"]["ToolCall"][];
        };
        /**
         * Graph
         * @description Red de co-ocurrencia, no un grafo de relaciones inferidas.
         */
        Graph: {
            /** Phenomenon */
            phenomenon?: number | null;
            /** Min Documents */
            min_documents: number;
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
        };
        /**
         * GraphEdge
         * @description Una arista de co-ocurrencia: el peso son los documentos compartidos.
         *
         *     `trace` es el fragmento concreto en el que las dos entidades coinciden: seleccionar una arista
         *     tiene que llevar al texto que la sustenta, no solo al documento.
         */
        GraphEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Documents */
            documents: number;
            trace: components["schemas"]["Trace"];
        };
        /** GraphNode */
        GraphNode: {
            /** Entity Id */
            entity_id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Documents */
            documents: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Matrix
         * @description Matriz de calor: dos variables categoricas y una numerica en el color.
         */
        Matrix: {
            /** Rows */
            rows: components["schemas"]["MatrixRow"][];
            /** Cols */
            cols: string[];
            /** Cols Field */
            cols_field: string;
            /** Phenomenon */
            phenomenon?: number | null;
            /** Cells */
            cells: components["schemas"]["MatrixCell"][];
        };
        /**
         * MatrixCell
         * @description Una celda: el cruce de dos categorias, con el fragmento que la sustenta.
         */
        MatrixCell: {
            /** Row Id */
            row_id: string;
            /** Row */
            row: string;
            /** Col */
            col: string;
            /** Documents */
            documents: number;
            /** Mentions */
            mentions: number;
            trace: components["schemas"]["Trace"];
        };
        /**
         * MatrixColumn
         * @description Segunda categoria de la matriz de calor.
         * @enum {string}
         */
        MatrixColumn: "observatory" | "phenomenon" | "language" | "format";
        /** MatrixRow */
        MatrixRow: {
            /** Entity Id */
            entity_id: string;
            /** Name */
            name: string;
        };
        /**
         * Metadata
         * @description Insumo de las metricas de eficiencia.
         */
        Metadata: {
            /**
             * Num Interacciones
             * @default 0
             */
            num_interacciones: number;
            /** Agentes Invocados */
            agentes_invocados?: string[];
            tokens?: components["schemas"]["Tokens"];
            /** Tokens Por Agente */
            tokens_por_agente?: components["schemas"]["AgentTokens"][];
            /**
             * Latencia Ms
             * @default 0
             */
            latencia_ms: number;
            /**
             * Estado
             * @default ok
             */
            estado: string;
        };
        /**
         * Phenomenon
         * @description Los tres fenomenos del reto.
         * @enum {integer}
         */
        Phenomenon: 1 | 2 | 3;
        /**
         * PlaceFeature
         * @description Un lugar como Feature de GeoJSON: el mapa lo consume tal cual.
         */
        PlaceFeature: {
            /**
             * Type
             * @default Feature
             */
            type: string;
            /** Id */
            id: string;
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            properties: components["schemas"]["PlaceProperties"];
        };
        /**
         * PlaceLevel
         * @description Nivel territorial del mapa. El zoom del anexo pide cambiar de agregacion, no de fuente.
         * @enum {string}
         */
        PlaceLevel: "country" | "department";
        /** PlaceProperties */
        PlaceProperties: {
            /** Place Id */
            place_id: string;
            /** Name */
            name: string;
            /** Iso2 */
            iso2?: string | null;
            /** Documents */
            documents: number;
            /** Mentions */
            mentions: number;
            trace: components["schemas"]["Trace"];
        };
        /**
         * Places
         * @description FeatureCollection de GeoJSON con el conteo en las propiedades.
         */
        Places: {
            /**
             * Type
             * @default FeatureCollection
             */
            type: string;
            /** Level */
            level: string;
            /** Phenomenon */
            phenomenon?: number | null;
            /** Entity */
            entity?: string | null;
            /** Features */
            features: components["schemas"]["PlaceFeature"][];
        };
        /**
         * Quadrant
         * @description Cuadrante de priorizacion: intensidad contra tendencia, con las lineas de corte explicitas.
         */
        Quadrant: {
            /** Phenomenon */
            phenomenon?: number | null;
            /** Split Year */
            split_year: number;
            /** Median Documents */
            median_documents: number;
            /** Median Recent Share */
            median_recent_share: number;
            /** Dated Documents */
            dated_documents: number;
            /** Total Documents */
            total_documents: number;
            /** Points */
            points: components["schemas"]["QuadrantPoint"][];
        };
        /**
         * QuadrantPoint
         * @description Una entidad en el plano. Las dos coordenadas son conteos, no un indice inventado.
         */
        QuadrantPoint: {
            /** Entity Id */
            entity_id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Documents */
            documents: number;
            /** Recent */
            recent: number;
            /** Earlier */
            earlier: number;
            trace: components["schemas"]["Trace"];
        };
        /**
         * Timeline
         * @description Evolucion temporal por fuente.
         *
         *     `dated` y `total` dicen sobre cuantos documentos se puede afirmar algo; `series` son las fuentes
         *     que tienen barra propia, en el orden en que se apilan.
         */
        Timeline: {
            /** Phenomenon */
            phenomenon?: number | null;
            /** Entity */
            entity?: string | null;
            /** Dated Documents */
            dated_documents: number;
            /** Total Documents */
            total_documents: number;
            /** Series */
            series: string[];
            /** Points */
            points: components["schemas"]["TimelinePoint"][];
        };
        /**
         * TimelinePoint
         * @description Un ano: el total y cuanto aporto cada fuente, para apilar la barra.
         */
        TimelinePoint: {
            /** Year */
            year: number;
            /** Total */
            total: number;
            /** Sources */
            sources: {
                [key: string]: number;
            };
        };
        /**
         * Tokens
         * @description Consumo de toda la solucion, no solo del orquestador.
         */
        Tokens: {
            /**
             * Input
             * @default 0
             */
            input: number;
            /**
             * Output
             * @default 0
             */
            output: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /**
         * ToolCall
         * @description Una herramienta invocada, con sus parametros y lo que devolvio.
         */
        ToolCall: {
            /** Name */
            name: string;
            /** Input Parameters */
            input_parameters?: {
                [key: string]: unknown;
            };
            /**
             * Output
             * @default
             */
            output: string;
        };
        /**
         * Trace
         * @description De donde sale un dato. Todo lo que el tablero muestra tiene que poder rastrearse.
         */
        Trace: {
            /** Doc Id */
            doc_id: string;
            /** Chunk Id */
            chunk_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    metadata_breakdown_metadata_breakdown_get: {
        parameters: {
            query: {
                /** @description Campo por el que agrupar */
                by: components["schemas"]["BreakdownField"];
                /** @description Limitar a un fenomeno */
                phenomenon?: components["schemas"]["Phenomenon"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Breakdown"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_documents__doc_id__get: {
        parameters: {
            query?: {
                /** @description Fragmento en el que centrar la ventana */
                around?: string | null;
                /** @description Primer fragmento de la ventana */
                start?: number;
            };
            header?: never;
            path: {
                /** @description Identificador del documento */
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entity_matrix_entities_matrix_get: {
        parameters: {
            query?: {
                /** @description Segunda categoria */
                cols?: components["schemas"]["MatrixColumn"];
                /** @description Limitar a un fenomeno */
                phenomenon?: components["schemas"]["Phenomenon"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Matrix"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entity_cooccurrence_entities_cooccurrence_get: {
        parameters: {
            query?: {
                /** @description Centrar la red en una entidad */
                entity?: string | null;
                /** @description Limitar a un fenomeno */
                phenomenon?: components["schemas"]["Phenomenon"] | null;
                /** @description Documentos compartidos minimos */
                min_documents?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Graph"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    places_places_get: {
        parameters: {
            query?: {
                /** @description Nivel territorial */
                level?: components["schemas"]["PlaceLevel"];
                /** @description Limitar a un fenomeno */
                phenomenon?: components["schemas"]["Phenomenon"] | null;
                /** @description Cuantos lugares devolver */
                limit?: number;
                /** @description Solo documentos que nombran la entidad */
                entity?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Places"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeline_timeline_get: {
        parameters: {
            query?: {
                /** @description Limitar a un fenomeno */
                phenomenon?: components["schemas"]["Phenomenon"] | null;
                /** @description Solo documentos que nombran la entidad */
                entity?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entity_quadrant_entities_quadrant_get: {
        parameters: {
            query?: {
                /** @description Limitar a un fenomeno */
                phenomenon?: components["schemas"]["Phenomenon"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quadrant"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_card_agent_card_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentCard"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
