/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/metadata/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Conteos por un campo de la metadata
         * @description Alimenta el componente de barras: comparacion, distribucion y composicion.
         */
        get: operations["metadata_breakdown_metadata_breakdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * El documento y sus fragmentos
         * @description El texto original detras de cualquier dato del tablero.
         */
        get: operations["document_documents__doc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Matriz de calor de entidades
         * @description Cruza las entidades mas presentes con otra categoria: que entidad domina cada fuente.
         */
        get: operations["entity_matrix_entities_matrix_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/cooccurrence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Red de co-ocurrencia de entidades
         * @description Que entidades aparecen juntas, y en cuantos documentos.
         */
        get: operations["entity_cooccurrence_entities_cooccurrence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lugares nombrados en el corpus
         * @description Alimenta el mapa coropletico. Solo devuelve lugares que el corpus nombra.
         */
        get: operations["places_places_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Documentos por ano
         * @description Alimenta la linea de tiempo. Sin fechas precomputadas la serie sale vacia a proposito:
         *     inventar una fecha desde el texto seria presentar una variable sin sustento.
         */
        get: operations["timeline_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Lo que mira el healthcheck del contenedor antes de dar el servicio por arriba.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Breakdown
         * @description Comparacion, distribucion y composicion sobre la metadata del corpus.
         */
        Breakdown: {
            /** Field */
            field: string;
            /** Phenomenon */
            phenomenon?: number | null;
            /** Total Fragments */
            total_fragments: number;
            /** Total Documents */
            total_documents: number;
            /** Buckets */
            buckets: components["schemas"]["BreakdownBucket"][];
        };
        /**
         * BreakdownBucket
         * @description Una barra: cuantos fragmentos y de cuantos documentos distintos.
         */
        BreakdownBucket: {
            /** Label */
            label: string;
            /** Fragments */
            fragments: number;
            /** Documents */
            documents: number;
        };
        /**
         * BreakdownField
         * @description Campos por los que se puede agrupar el corpus. Lista cerrada: son columnas indexadas.
         * @enum {string}
         */
        BreakdownField: "phenomenon" | "observatory" | "language" | "format";
        /**
         * Document
         * @description El texto original que sustenta una visualizacion.
         */
        Document: {
            /** Doc Id */
            doc_id: string;
            /** Title */
            title?: string | null;
            /** Observatory */
            observatory?: string | null;
            /** Phenomenon */
            phenomenon: number;
            /** Language */
            language?: string | null;
            /** Format */
            format?: string | null;
            /** Fragments */
            fragments?: components["schemas"]["DocumentFragment"][];
        };
        /** DocumentFragment */
        DocumentFragment: {
            /** Chunk Id */
            chunk_id: string;
            /** Position */
            position: number;
            /** Num Tokens */
            num_tokens: number;
            /** Text */
            text: string;
        };
        /**
         * Graph
         * @description Red de co-ocurrencia, no un grafo de relaciones inferidas.
         */
        Graph: {
            /** Phenomenon */
            phenomenon?: number | null;
            /** Min Documents */
            min_documents: number;
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
        };
        /**
         * GraphEdge
         * @description Una arista de co-ocurrencia: el peso son los documentos compartidos.
         */
        GraphEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Documents */
            documents: number;
            /** Sample Doc */
            sample_doc: string;
        };
        /** GraphNode */
        GraphNode: {
            /** Entity Id */
            entity_id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Documents */
            documents: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Matrix
         * @description Matriz de calor: dos variables categoricas y una numerica en el color.
         */
        Matrix: {
            /** Rows */
            rows: string[];
            /** Cols */
            cols: string[];
            /** Cols Field */
            cols_field: string;
            /** Phenomenon */
            phenomenon?: number | null;
            /** Cells */
            cells: components["schemas"]["MatrixCell"][];
        };
        /**
         * MatrixCell
         * @description Una celda: el cruce de dos categorias, con el fragmento que la sustenta.
         */
        MatrixCell: {
            /** Row */
            row: string;
            /** Col */
            col: string;
            /** Documents */
            documents: number;
            /** Mentions */
            mentions: number;
            trace: components["schemas"]["Trace"];
        };
        /**
         * MatrixColumn
         * @description Segunda categoria de la matriz de calor.
         * @enum {string}
         */
        MatrixColumn: "observatory" | "phenomenon" | "language" | "format";
        /**
         * Phenomenon
         * @description Los tres fenomenos del reto.
         * @enum {integer}
         */
        Phenomenon: 1 | 2 | 3;
        /**
         * PlaceFeature
         * @description Un lugar como Feature de GeoJSON: el mapa lo consume tal cual.
         */
        PlaceFeature: {
            /**
             * Type
             * @default Feature
             */
            type: string;
            /** Id */
            id: string;
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            properties: components["schemas"]["PlaceProperties"];
        };
        /**
         * PlaceLevel
         * @description Nivel territorial del mapa. El zoom del anexo pide cambiar de agregacion, no de fuente.
         * @enum {string}
         */
        PlaceLevel: "country" | "department";
        /** PlaceProperties */
        PlaceProperties: {
            /** Place Id */
            place_id: string;
            /** Name */
            name: string;
            /** Documents */
            documents: number;
            /** Mentions */
            mentions: number;
            trace: components["schemas"]["Trace"];
        };
        /**
         * Places
         * @description FeatureCollection de GeoJSON con el conteo en las propiedades.
         */
        Places: {
            /**
             * Type
             * @default FeatureCollection
             */
            type: string;
            /** Level */
            level: string;
            /** Phenomenon */
            phenomenon?: number | null;
            /** Features */
            features: components["schemas"]["PlaceFeature"][];
        };
        /**
         * Timeline
         * @description Evolucion temporal. `dated` y `total` dicen sobre cuantos documentos se puede afirmar algo.
         */
        Timeline: {
            /** Phenomenon */
            phenomenon?: number | null;
            /** Entity */
            entity?: string | null;
            /** Dated Documents */
            dated_documents: number;
            /** Total Documents */
            total_documents: number;
            /** Points */
            points: components["schemas"]["TimelinePoint"][];
        };
        /** TimelinePoint */
        TimelinePoint: {
            /** Year */
            year: number;
            /** Documents */
            documents: number;
        };
        /**
         * Trace
         * @description De donde sale un dato. Todo lo que el tablero muestra tiene que poder rastrearse.
         */
        Trace: {
            /** Doc Id */
            doc_id: string;
            /** Chunk Id */
            chunk_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    metadata_breakdown_metadata_breakdown_get: {
        parameters: {
            query: {
                /** @description Campo por el que agrupar */
                by: components["schemas"]["BreakdownField"];
                /** @description Limitar a un fenomeno */
                phenomenon?: components["schemas"]["Phenomenon"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Breakdown"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_documents__doc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entity_matrix_entities_matrix_get: {
        parameters: {
            query?: {
                /** @description Segunda categoria */
                cols?: components["schemas"]["MatrixColumn"];
                /** @description Limitar a un fenomeno */
                phenomenon?: components["schemas"]["Phenomenon"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Matrix"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entity_cooccurrence_entities_cooccurrence_get: {
        parameters: {
            query?: {
                /** @description Centrar la red en una entidad */
                entity?: string | null;
                /** @description Limitar a un fenomeno */
                phenomenon?: components["schemas"]["Phenomenon"] | null;
                /** @description Documentos compartidos minimos */
                min_documents?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Graph"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    places_places_get: {
        parameters: {
            query?: {
                /** @description Nivel territorial */
                level?: components["schemas"]["PlaceLevel"];
                /** @description Limitar a un fenomeno */
                phenomenon?: components["schemas"]["Phenomenon"] | null;
                /** @description Cuantos lugares devolver */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Places"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeline_timeline_get: {
        parameters: {
            query?: {
                /** @description Limitar a un fenomeno */
                phenomenon?: components["schemas"]["Phenomenon"] | null;
                /** @description Solo documentos que nombran la entidad */
                entity?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
