/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/metadata/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Conteos por un campo de la metadata
         * @description Alimenta el componente de barras: comparacion, distribucion y composicion.
         */
        get: operations["metadata_breakdown_metadata_breakdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metadata/distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Distribucion de una medida por documento
         * @description Alimenta el histograma: como se reparten la longitud o las entidades de los documentos.
         */
        get: operations["metadata_distribution_metadata_distribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * El documento y sus fragmentos
         * @description El texto original detras de cualquier dato del tablero, en la ventana que contiene `around`.
         *
         *     Sin `around`, la ventana empieza en `start`. Centrarla en el fragmento citado es lo que cierra
         *     la trazabilidad que exige la especificacion: el dato lleva a su `chunk_id`, no solo al `doc_id`.
         */
        get: operations["document_documents__doc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Matriz de calor de entidades
         * @description Cruza las entidades mas presentes con otra categoria: que entidad domina cada fuente.
         */
        get: operations["entity_matrix_entities_matrix_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/cooccurrence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Red de co-ocurrencia de entidades
         * @description Que entidades aparecen juntas, y en cuantos documentos.
         */
        get: operations["entity_cooccurrence_entities_cooccurrence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lugares nombrados en el corpus
         * @description Alimenta el mapa coropletico. Solo devuelve lugares que el corpus nombra.
         */
        get: operations["places_places_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Documentos por ano
         * @description Alimenta la linea de tiempo. Sin fechas precomputadas la serie sale vacia a proposito:
         *     inventar una fecha desde el texto seria presentar una variable sin sustento.
         */
        get: operations["timeline_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/quadrant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cuadrante de priorizacion de entidades
         * @description Intensidad contra tendencia: a que entidades mirar primero, sin puntuar ninguna.
         *
         *     El eje horizontal son los documentos que nombran la entidad y el vertical, que proporcion de
         *     ellos esta en la mitad reciente del corpus. Los dos son conteos verificables; las lineas de
         *     corte son las medianas, asi que el cuadrante compara entidades entre si y no contra un umbral
         *     inventado.
         */
        get: operations["entity_quadrant_entities_quadrant_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Presencia de grupos armados en la cuenca amazonica
         * @description Que grupos armados registra cada territorio, y en que municipios.
         *
         *     El dato viene por municipio, pero la geometria municipal no esta en el indice: el mapa agrega al
         *     territorio de nivel 1 —departamento, estado o provincia, segun el pais— y la lista conserva el
         *     municipio, que es donde la fuente mide. Cubre los seis paises de la cuenca amazonica.
         *
         *     Es un conteo de presencia declarada por la fuente, no una medida de intensidad ni de riesgo.
         */
        get: operations["presence_presence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alertas tempranas de la Defensoria del Pueblo
         * @description Donde y cuando se emitieron alertas, separando el riesgo inminente del estructural.
         *
         *     Una alerta de alcance nacional nombra varios departamentos y cuenta en cada uno: la cifra es
         *     "alertas que nombran el territorio", no "alertas sobre el territorio", y la vista lo declara.
         *
         *     Las alertas son documentos del corpus, asi que `entity` las recorta igual que al resto del
         *     tablero: es el filtro global, no uno propio de esta vista.
         */
        get: operations["alerts_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/territories/{place_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Todo lo que el radar sabe de un territorio
         * @description La evidencia de un territorio, para el detalle de la barra lateral.
         *
         *     Las tres secciones vienen de fuentes distintas y pueden no coincidir: un municipio puede
         *     registrar presencia armada sin que ningun documento del corpus lo nombre, y eso es informacion,
         *     no un error. Cada seccion declara de donde sale.
         */
        get: operations["territory_territories__place_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pregunta al asistente del radar
         * @description Una pregunta, una respuesta con su evidencia y su coste.
         */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Lo que mira el healthcheck del contenedor.
         *
         *     Comprueba la base de datos: un proceso que responde pero no puede consultar el corpus esta
         *     caido a efectos de la demo, y marcarlo sano solo retrasa el diagnostico.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentTokens
         * @description El gasto de una capa. Sumados dan `metadata.tokens`, nunca solo el del orquestador.
         */
        AgentTokens: {
            /** Input */
            input: number;
            /** Output */
            output: number;
            /** Total */
            total: number;
            /** Agente */
            agente: string;
            /** Modelo */
            modelo: string;
        };
        /**
         * Alert
         * @description Una alerta concreta, con su codigo y el fragmento donde consta.
         */
        Alert: {
            /** Doc Id */
            doc_id: string;
            /** Code */
            code: string;
            /** Kind */
            kind: string;
            /** Issued On */
            issued_on?: string | null;
            trace: components["schemas"]["Trace"];
        };
        /** AlertFeature */
        AlertFeature: {
            /**
             * Type
             * @default Feature
             */
            type: string;
            /** Id */
            id: string;
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            properties: components["schemas"]["AlertProperties"];
        };
        /**
         * AlertProperties
         * @description Lo que el mapa pinta de un departamento: cuantas alertas de cada clase lo nombran.
         */
        AlertProperties: {
            /** Place Id */
            place_id: string;
            /** Name */
            name: string;
            /** Iso2 */
            iso2?: string | null;
            /** Alerts */
            alerts: number;
            /** Imminent */
            imminent: number;
            /** Structural */
            structural: number;
            /** Latest */
            latest?: string | null;
            trace: components["schemas"]["Trace"];
        };
        /** AlertYear */
        AlertYear: {
            /** Year */
            year: number;
            /** Alerts */
            alerts: number;
            /** Imminent */
            imminent: number;
            /** Structural */
            structural: number;
            trace: components["schemas"]["Trace"];
        };
        /**
         * Alerts
         * @description Alertas tempranas de la Defensoria del Pueblo.
         *
         *     `imminent` y `structural` van siempre separadas: una declara una amenaza inmediata y la otra una
         *     sostenida en el tiempo, y sumarlas daria una cifra sin significado.
         */
        Alerts: {
            /** Kind */
            kind?: string | null;
            /** Alerts */
            alerts: number;
            /** Imminent */
            imminent: number;
            /** Structural */
            structural: number;
            /** Since */
            since?: string | null;
            /** Until */
            until?: string | null;
            /** Features */
            features: components["schemas"]["AlertFeature"][];
            /** Years */
            years: components["schemas"]["AlertYear"][];
            /** Recent */
            recent: components["schemas"]["Alert"][];
        };
        /** ArmedGroup */
        ArmedGroup: {
            /** Name */
            name: string;
            /** Municipalities */
            municipalities: number;
            trace: components["schemas"]["Trace"];
        };
        /**
         * Breakdown
         * @description Comparacion, distribucion y composicion sobre la metadata del corpus.
         */
        Breakdown: {
            /** Field */
            field: string;
            /** Phenomenon */
            phenomenon?: number | null;
            /** Total Fragments */
            total_fragments: number;
            /** Total Documents */
            total_documents: number;
            /** Buckets */
            buckets: components["schemas"]["BreakdownBucket"][];
        };
        /**
         * BreakdownBucket
         * @description Una barra: cuantos fragmentos y de cuantos documentos distintos.
         */
        BreakdownBucket: {
            /** Label */
            label: string;
            /** Fragments */
            fragments: number;
            /** Documents */
            documents: number;
            trace: components["schemas"]["Trace"];
        };
        /**
         * BreakdownField
         * @description Campos por los que se puede agrupar el corpus. Lista cerrada: son columnas indexadas.
         * @enum {string}
         */
        BreakdownField: "phenomenon" | "observatory" | "language" | "format";
        /**
         * ChatRequest
         * @description La pregunta del usuario. `input` es lo que manda el frontend de chat ya construido.
         */
        ChatRequest: {
            /** Input */
            input: string;
        };
        /**
         * ChatResponse
         * @description La respuesta del endpoint, con la estructura exacta que exige la especificacion.
         */
        ChatResponse: {
            /** Respuesta */
            respuesta: string;
            evaluacion: components["schemas"]["Evaluation"];
            metadata: components["schemas"]["Metadata"];
        };
        /**
         * Distribution
         * @description Como se reparte una medida por documento, con sus cuartiles.
         *
         *     Los tramos son potencias de dos: la medida tiene una cola larga (la mediana de fragmentos por
         *     documento va de 1 a 8 segun el fenomeno y el p95 pasa de 100), y con tramos iguales todo caeria
         *     en la primera barra.
         */
        Distribution: {
            /** Measure */
            measure: string;
            /** Phenomenon */
            phenomenon?: number | null;
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
            /** Documents */
            documents: number;
            /** Quartiles */
            quartiles: number[];
            /** Bins */
            bins: components["schemas"]["DistributionBin"][];
        };
        /**
         * DistributionBin
         * @description Un tramo del histograma: documentos cuyo valor cae entre `low` y `high`, por fenomeno.
         */
        DistributionBin: {
            /** Label */
            label: string;
            /** Low */
            low: number;
            /** High */
            high?: number | null;
            /** Documents */
            documents: number;
            /** By Phenomenon */
            by_phenomenon: {
                [key: string]: number;
            };
            trace?: components["schemas"]["Trace"] | null;
        };
        /**
         * DistributionMeasure
         * @description Medidas por documento cuya distribucion se puede pedir.
         * @enum {string}
         */
        DistributionMeasure: "fragments" | "entities";
        /**
         * Document
         * @description El texto original que sustenta una visualizacion, en una ventana de sus fragmentos.
         *
         *     `total` y `start` situan la ventana dentro del documento: el lector sabe cuanto queda a cada
         *     lado y puede pedir el tramo anterior o el siguiente sin traerse el documento entero.
         */
        Document: {
            /** Doc Id */
            doc_id: string;
            /** Title */
            title?: string | null;
            /** Observatory */
            observatory?: string | null;
            /** Phenomenon */
            phenomenon: number;
            /** Language */
            language?: string | null;
            /** Format */
            format?: string | null;
            /** Total */
            total: number;
            /** Start */
            start: number;
            /** Fragments */
            fragments?: components["schemas"]["DocumentFragment"][];
        };
        /** DocumentFragment */
        DocumentFragment: {
            /** Chunk Id */
            chunk_id: string;
            /** Position */
            position: number;
            /** Num Tokens */
            num_tokens: number;
            /** Text */
            text: string;
        };
        /**
         * Evaluation
         * @description Lo que la organizacion mide: relevancia, fidelidad y trazabilidad de la respuesta.
         */
        Evaluation: {
            /** Input */
            input: string;
            /** Actual Output */
            actual_output: string;
            /** Retrieval Context */
            retrieval_context?: string[] | null;
            /** Tools Called */
            tools_called?: components["schemas"]["ToolCall"][];
        };
        /**
         * Graph
         * @description Red de co-ocurrencia, no un grafo de relaciones inferidas.
         */
        Graph: {
            /** Phenomenon */
            phenomenon?: number | null;
            /** Min Documents */
            min_documents: number;
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
        };
        /**
         * GraphEdge
         * @description Una arista de co-ocurrencia: el peso son los documentos compartidos.
         *
         *     `trace` es el fragmento concreto en el que las dos entidades coinciden: seleccionar una arista
         *     tiene que llevar al texto que la sustenta, no solo al documento.
         */
        GraphEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Documents */
            documents: number;
            trace: components["schemas"]["Trace"];
        };
        /** GraphNode */
        GraphNode: {
            /** Entity Id */
            entity_id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Documents */
            documents: number;
            trace: components["schemas"]["Trace"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Matrix
         * @description Matriz de calor: dos variables categoricas y una numerica en el color.
         */
        Matrix: {
            /** Rows */
            rows: components["schemas"]["MatrixRow"][];
            /** Cols */
            cols: string[];
            /** Cols Field */
            cols_field: string;
            /** Phenomenon */
            phenomenon?: number | null;
            /** Cells */
            cells: components["schemas"]["MatrixCell"][];
        };
        /**
         * MatrixCell
         * @description Una celda: el cruce de dos categorias, con el fragmento que la sustenta.
         */
        MatrixCell: {
            /** Row Id */
            row_id: string;
            /** Row */
            row: string;
            /** Col */
            col: string;
            /** Documents */
            documents: number;
            /** Mentions */
            mentions: number;
            trace: components["schemas"]["Trace"];
        };
        /**
         * MatrixColumn
         * @description Segunda categoria de la matriz de calor.
         * @enum {string}
         */
        MatrixColumn: "observatory" | "phenomenon" | "language" | "format";
        /** MatrixRow */
        MatrixRow: {
            /** Entity Id */
            entity_id: string;
            /** Name */
            name: string;
        };
        /**
         * Metadata
         * @description El coste y el recorrido de la respuesta. `num_interacciones` son llamadas a modelo.
         */
        Metadata: {
            /** Num Interacciones */
            num_interacciones: number;
            /** Agentes Invocados */
            agentes_invocados: string[];
            tokens: components["schemas"]["Tokens"];
            /** Tokens Por Agente */
            tokens_por_agente: components["schemas"]["AgentTokens"][];
            /** Latencia Ms */
            latencia_ms: number;
            /** Estado */
            estado: string;
        };
        /**
         * Municipality
         * @description El nivel en el que la fuente da el dato, con su traza al fragmento que lo sustenta.
         */
        Municipality: {
            /** Pcode */
            pcode: string;
            /** Country */
            country: string;
            /** Admin1 */
            admin1: string;
            /** Admin2 */
            admin2: string;
            /** Population */
            population?: number | null;
            /** Groups */
            groups: string[];
            /** No Info */
            no_info: boolean;
            trace: components["schemas"]["Trace"];
        };
        /**
         * MunicipalityFeature
         * @description Un municipio como Feature de GeoJSON: es donde la fuente mide, y donde el mapa lo pinta.
         */
        MunicipalityFeature: {
            /**
             * Type
             * @default Feature
             */
            type: string;
            /** Id */
            id: string;
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            properties: components["schemas"]["Municipality"];
        };
        /**
         * Phenomenon
         * @description Los tres fenomenos del reto.
         * @enum {integer}
         */
        Phenomenon: 1 | 2 | 3;
        /**
         * PlaceFeature
         * @description Un lugar como Feature de GeoJSON: el mapa lo consume tal cual.
         */
        PlaceFeature: {
            /**
             * Type
             * @default Feature
             */
            type: string;
            /** Id */
            id: string;
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            properties: components["schemas"]["PlaceProperties"];
        };
        /**
         * PlaceFragment
         * @description Un fragmento que nombra el territorio, con lo justo para juzgarlo y abrirlo entero.
         */
        PlaceFragment: {
            /** Doc Id */
            doc_id: string;
            /** Chunk Id */
            chunk_id: string;
            /** Phenomenon */
            phenomenon: number;
            /** Observatory */
            observatory?: string | null;
            /** Language */
            language?: string | null;
            /** Mentions */
            mentions: number;
            /** Excerpt */
            excerpt: string;
            /** Truncated */
            truncated: boolean;
        };
        /**
         * PlaceLevel
         * @description Nivel territorial del mapa. El zoom del anexo pide cambiar de agregacion, no de fuente.
         * @enum {string}
         */
        PlaceLevel: "country" | "department";
        /** PlaceProperties */
        PlaceProperties: {
            /** Place Id */
            place_id: string;
            /** Name */
            name: string;
            /** Iso2 */
            iso2?: string | null;
            /** Documents */
            documents: number;
            /** Mentions */
            mentions: number;
            trace: components["schemas"]["Trace"];
        };
        /**
         * Places
         * @description FeatureCollection de GeoJSON con el conteo en las propiedades.
         */
        Places: {
            /**
             * Type
             * @default FeatureCollection
             */
            type: string;
            /** Level */
            level: string;
            /** Phenomenon */
            phenomenon?: number | null;
            /** Entity */
            entity?: string | null;
            /** Date From */
            date_from?: string | null;
            /** Date To */
            date_to?: string | null;
            /** Features */
            features: components["schemas"]["PlaceFeature"][];
        };
        /**
         * Presence
         * @description Presencia de grupos armados en la cuenca amazonica.
         *
         *     El mapa agrega al departamento porque es el territorio con geometria; la lista conserva el
         *     municipio, que es donde la fuente mide. Un municipio sin grupos y con `no_info` es *sin
         *     informacion*, no *sin presencia*, y las dos cifras van separadas por eso.
         */
        Presence: {
            /** Group */
            group?: string | null;
            /** Country */
            country?: string | null;
            /** Municipalities */
            municipalities: number;
            /** With Presence */
            with_presence: number;
            /** Without Information */
            without_information: number;
            /** Matching */
            matching: number;
            /** Groups */
            groups: components["schemas"]["ArmedGroup"][];
            /** Features */
            features: components["schemas"]["MunicipalityFeature"][];
            /** Regions */
            regions: components["schemas"]["PresenceFeature"][];
            /** Places */
            places: components["schemas"]["Municipality"][];
        };
        /** PresenceFeature */
        PresenceFeature: {
            /**
             * Type
             * @default Feature
             */
            type: string;
            /** Id */
            id: string;
            /** Geometry */
            geometry: {
                [key: string]: unknown;
            };
            properties: components["schemas"]["PresenceProperties"];
        };
        /**
         * PresenceProperties
         * @description Lo que el mapa pinta de un departamento: cuantos municipios suyos registran presencia.
         */
        PresenceProperties: {
            /** Place Id */
            place_id: string;
            /** Name */
            name: string;
            /** Iso2 */
            iso2?: string | null;
            /** Municipalities */
            municipalities: number;
            /** With Presence */
            with_presence: number;
            /** Without Information */
            without_information: number;
            /** Groups */
            groups: number;
            trace: components["schemas"]["Trace"];
        };
        /**
         * Quadrant
         * @description Cuadrante de priorizacion: intensidad contra tendencia, con las lineas de corte explicitas.
         */
        Quadrant: {
            /** Phenomenon */
            phenomenon?: number | null;
            /** Split Year */
            split_year: number;
            /** Median Documents */
            median_documents: number;
            /** Median Recent Share */
            median_recent_share: number;
            /** Dated Documents */
            dated_documents: number;
            /** Total Documents */
            total_documents: number;
            /** Points */
            points: components["schemas"]["QuadrantPoint"][];
        };
        /**
         * QuadrantPoint
         * @description Una entidad en el plano. Las dos coordenadas son conteos, no un indice inventado.
         */
        QuadrantPoint: {
            /** Entity Id */
            entity_id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Documents */
            documents: number;
            /** Recent */
            recent: number;
            /** Earlier */
            earlier: number;
            trace: components["schemas"]["Trace"];
        };
        /**
         * Territory
         * @description Todo lo que el radar sabe de un territorio: quien lo nombra, quien opera y que se alerto.
         *
         *     Es el nivel en el que el tablero deja de mostrar cifras y muestra evidencia: cada elemento lleva
         *     su `doc_id` y su `chunk_id`, y desde ahi se abre el documento por el fragmento exacto.
         */
        Territory: {
            /** Place Id */
            place_id: string;
            /** Name */
            name: string;
            /** Iso2 */
            iso2?: string | null;
            /** Level */
            level: string;
            /**
             * Forms
             * @default []
             */
            forms: string[];
            /** Phenomenon */
            phenomenon?: number | null;
            /** Total Fragments */
            total_fragments: number;
            /** Total Documents */
            total_documents: number;
            /** Fragments */
            fragments: components["schemas"]["PlaceFragment"][];
            /** Municipalities */
            municipalities: components["schemas"]["Municipality"][];
            /** Alerts */
            alerts: components["schemas"]["TerritoryAlert"][];
        };
        /**
         * TerritoryAlert
         * @description Una alerta que nombra el territorio.
         */
        TerritoryAlert: {
            /** Doc Id */
            doc_id: string;
            /** Code */
            code: string;
            /** Kind */
            kind: string;
            /** Issued On */
            issued_on?: string | null;
            /** Excerpt */
            excerpt: string;
            trace: components["schemas"]["Trace"];
        };
        /**
         * Timeline
         * @description Evolucion temporal por fenomeno o por fuente.
         *
         *     `dated` y `total` dicen sobre cuantos documentos se puede afirmar algo; `series` son lo que tiene
         *     barra propia, en el orden en que se apila: `F1`, `F2` y `F3` sin filtro de fenomeno, y las
         *     fuentes con el filtro puesto.
         */
        Timeline: {
            /** Phenomenon */
            phenomenon?: number | null;
            /** Entity */
            entity?: string | null;
            /** Dated Documents */
            dated_documents: number;
            /** Total Documents */
            total_documents: number;
            /** Series */
            series: string[];
            /** Points */
            points: components["schemas"]["TimelinePoint"][];
        };
        /**
         * TimelinePoint
         * @description Un ano: el total y cuanto aporto cada fuente, para apilar la barra.
         */
        TimelinePoint: {
            /** Year */
            year: number;
            /** Total */
            total: number;
            /** Sources */
            sources: {
                [key: string]: number;
            };
            trace: components["schemas"]["Trace"];
        };
        /** Tokens */
        Tokens: {
            /** Input */
            input: number;
            /** Output */
            output: number;
            /** Total */
            total: number;
        };
        /**
         * ToolCall
         * @description Una herramienta invocada. El tablero deduce de `name` que componente activar.
         */
        ToolCall: {
            /** Name */
            name: string;
            /** Input Parameters */
            input_parameters?: {
                [key: string]: unknown;
            };
            /** Output */
            output: string;
        };
        /**
         * Trace
         * @description De donde sale un dato. Todo lo que el tablero muestra tiene que poder rastrearse.
         */
        Trace: {
            /** Doc Id */
            doc_id: string;
            /** Chunk Id */
            chunk_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    metadata_breakdown_metadata_breakdown_get: {
        parameters: {
            query: {
                /** @description Campo por el que agrupar */
                by: components["schemas"]["BreakdownField"];
                /** @description Limitar a un fenomeno */
                phenomenon?: components["schemas"]["Phenomenon"] | null;
                /** @description Primer dia del periodo (ISO 8601); sin el, desde el principio */
                date_from?: string | null;
                /** @description Ultimo dia del periodo (ISO 8601); sin el, hasta el final */
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Breakdown"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metadata_distribution_metadata_distribution_get: {
        parameters: {
            query?: {
                /** @description Que se mide de cada documento */
                measure?: components["schemas"]["DistributionMeasure"];
                /** @description Limitar a un fenomeno */
                phenomenon?: components["schemas"]["Phenomenon"] | null;
                /** @description Primer dia del periodo (ISO 8601); sin el, desde el principio */
                date_from?: string | null;
                /** @description Ultimo dia del periodo (ISO 8601); sin el, hasta el final */
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Distribution"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_documents__doc_id__get: {
        parameters: {
            query?: {
                /** @description Fragmento en el que centrar la ventana */
                around?: string | null;
                /** @description Primer fragmento de la ventana */
                start?: number;
            };
            header?: never;
            path: {
                /** @description Identificador del documento */
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entity_matrix_entities_matrix_get: {
        parameters: {
            query?: {
                /** @description Segunda categoria */
                cols?: components["schemas"]["MatrixColumn"];
                /** @description Limitar a un fenomeno */
                phenomenon?: components["schemas"]["Phenomenon"] | null;
                /** @description Primer dia del periodo (ISO 8601); sin el, desde el principio */
                date_from?: string | null;
                /** @description Ultimo dia del periodo (ISO 8601); sin el, hasta el final */
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Matrix"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entity_cooccurrence_entities_cooccurrence_get: {
        parameters: {
            query?: {
                /** @description Centrar la red en una entidad */
                entity?: string | null;
                /** @description Limitar a un fenomeno */
                phenomenon?: components["schemas"]["Phenomenon"] | null;
                /** @description Documentos compartidos minimos */
                min_documents?: number;
                /** @description Primer dia del periodo (ISO 8601); sin el, desde el principio */
                date_from?: string | null;
                /** @description Ultimo dia del periodo (ISO 8601); sin el, hasta el final */
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Graph"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    places_places_get: {
        parameters: {
            query?: {
                /** @description Nivel territorial */
                level?: components["schemas"]["PlaceLevel"];
                /** @description Limitar a un fenomeno */
                phenomenon?: components["schemas"]["Phenomenon"] | null;
                /** @description Cuantos lugares devolver */
                limit?: number;
                /** @description Solo documentos que nombran la entidad */
                entity?: string | null;
                /** @description Primer dia del periodo (ISO 8601); sin el, desde el principio */
                date_from?: string | null;
                /** @description Ultimo dia del periodo (ISO 8601); sin el, hasta el final */
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Places"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeline_timeline_get: {
        parameters: {
            query?: {
                /** @description Limitar a un fenomeno */
                phenomenon?: components["schemas"]["Phenomenon"] | null;
                /** @description Solo documentos que nombran la entidad */
                entity?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entity_quadrant_entities_quadrant_get: {
        parameters: {
            query?: {
                /** @description Limitar a un fenomeno */
                phenomenon?: components["schemas"]["Phenomenon"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quadrant"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    presence_presence_get: {
        parameters: {
            query?: {
                /** @description Limitar a un grupo armado */
                group?: string | null;
                /** @description Limitar la lista a un pais */
                country?: string | null;
                /** @description Cuantos municipios listar */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Presence"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alerts_alerts_get: {
        parameters: {
            query?: {
                /** @description Inminencia o Estructural */
                kind?: string | null;
                /** @description Solo alertas que nombran la entidad */
                entity?: string | null;
                /** @description Cuantas alertas recientes listar */
                limit?: number;
                /** @description Primer dia del periodo (ISO 8601); sin el, desde el principio */
                date_from?: string | null;
                /** @description Ultimo dia del periodo (ISO 8601); sin el, hasta el final */
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alerts"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    territory_territories__place_id__get: {
        parameters: {
            query?: {
                /** @description Limitar a un fenomeno */
                phenomenon?: components["schemas"]["Phenomenon"] | null;
                /** @description Limitar los municipios a un grupo */
                group?: string | null;
                /** @description Limitar las alertas a una clase de riesgo */
                kind?: string | null;
                /** @description Cuantos fragmentos devolver */
                limit?: number;
                /** @description Solo documentos que nombran la entidad */
                entity?: string | null;
                /** @description Primer dia del periodo (ISO 8601); sin el, desde el principio */
                date_from?: string | null;
                /** @description Ultimo dia del periodo (ISO 8601); sin el, hasta el final */
                date_to?: string | null;
            };
            header?: never;
            path: {
                /** @description Pais o departamento */
                place_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Territory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
